### ISSUE TITLE
Cannot install with Cabal 2.1

### ISSUE THREAD

**Issue by tfausak** [ekmett/distributive#37]
I am working on a project that requires features from the latest HEAD version of `Cabal` (see https://github.com/haskell/cabal/issues/4799). Something in my dependency tree pulled in `distributive` which caused my build to fail with this error:

```
Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for cabal-doctest-1.0.2:
    Cabal-2.1.0.0 must match >=1.10 && <2.1 (latest applicable is 2.0.0.2)
needed due to example-0.0.0 -> cabal-doctest-1.0.2

Plan construction failed.
```

This puzzled me because I wasn't trying to build tests for any of my dependencies. Why is `cabal-doctest` needed for `distributive`'s `Setup.lhs`? 

I ran into this problem with Stack 1.5.1. I assume the same thing happens with cabal-install. Here is a minimal way to reproduce the problem:

``` yaml
# stack.yaml
resolver: lts-9.0

packages:
  - .
  - extra-dep: true
    location:
      commit: 4009c986805cd2648a980d6e88f4c50a38a43410
      git: https://github.com/haskell/cabal
    subdirs:
      - Cabal

extra-deps:
  - distributive-0.5.3
```

``` yaml
# package.yaml
name: example
version: 0.0.0

library:
  dependencies:
    - Cabal
    - distributive
```
